### ISSUE TITLE
Which better version

### ISSUE THREAD

**Issue by lowburger** [lsp199308/sys-patch#1]
Hi,

Which better version?

https://github.com/lsp199308/sys-patch

or

https://github.com/lsp199308/sys-patch-two

Thx

**Comment by lsp199308** [comment]
> Hi,
> 
> 
> 
> Which better version?
> 
> 
> 
> https://github.com/lsp199308/sys-patch
> 
> 
> 
> or
> 
> 
> 
> https://github.com/lsp199308/sys-patch-two
> 
> 
> 
> Thx

Above fw17, there is no difference between them. I have pushed them to the official sys patch.
